serial_interfaces:
- device: /dev/ttyUSB0
  baudrate: 4000000
  protocol: native
  motors:
  - name: strike_motor_L1
    type: GO8010
    id: 0
    direction: -1
    offset: -0.376467
    gear_ratio: 6.33
    k_pos: 0.01
    k_spd: 0.005
  - name: strike_motor_L2
    type: GO8010
    id: 1
    direction: 1
    offset: 0.566186
    gear_ratio: 6.33
    k_pos: 0.01
    k_spd: 0.005
- device: /dev/ttyUSB1
  baudrate: 4000000
  protocol: native
  motors:
  - name: strike_motor_R1
    type: GO8010
    id: 2
    direction: 1

    offset: 0.773200
    gear_ratio: 6.33
    k_pos: 0.01
    k_spd: 0.005
  - name: strike_motor_R2
    type: GO8010
    id: 3
    direction: -1
    offset: -0.977277
    gear_ratio: 6.33
    k_pos: 0.01
    k_spd: 0.005
